; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanorp2040connect]
platform = raspberrypi
board = nanorp2040connect
framework = arduino
build_src_filter = -<*> +<nano/>
lib_deps = 
    denyssene/SimpleKalmanFilter@^0.1.0
    arduino-libraries/Arduino_LSM6DSOX@^1.1.2
    arduino-libraries/ArduinoBLE@^2.1.0

[env:esp32]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = -<*> +<esp/>
# JANGAN ADA lib_deps DI ENV INI, MASUKKIN AJA SEMUA KE nanorp2040connect BIAR CLANGD GA ERROR MULU

# UPDATE -> pio run -e nanorp2040connect -t compiledb
