; PlatformIO Project Configuration File for ESP32 SmartKey Receiver / Door Lock
[platformio]
default_envs = esp32

[env:esp32]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200